spring.application.name=Enotes

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/enotes
spring.datasource.username=postgres
spring.datasource.password=123456789

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect